In [18]:
from transformers import T5Tokenizer, T5ForConditionalGeneration
from utils_accelerate import *

tokenizer = T5Tokenizer.from_pretrained('t5-small')
# input = "predict tail: barack obama | position_held |"
# input = "translate English to German: How are you doing?"

# model = T5ForConditionalGeneration.from_pretrained('models/codex_m_accelerate_1gpu.pt')
checkpoint_location = 'models/codex_m_accelerate_1gpu/115000.pt'
# checkpoint_location = 'models/codex-m_tiny/70000.pt'
# checkpoint_location = 'models/codex-m_small_6gpu/45000.pt'
model = load_accelerator_model(checkpoint_location, only_model=True)
model.eval()
model.cpu()

Model args
Namespace(batch_size=64, dataset='codex-m', epochs=20, learning_rate=None, load_checkpoint=None, loss_steps=500, max_checkpoints=5, model_size='small', num_workers=3, optimizer='adafactor', resume=None, save_prefix='codex_m_accelerate_1gpu', save_steps=5000, start_steps=0)


T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseReluDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dro

In [2]:
input = "predict tail: united states of america | member of |"
input_ids = tokenizer(input, return_tensors="pt").input_ids  # Batch size 1
model.cpu()


T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseReluDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dro

In [3]:
# outputs = model.sample(input_ids)
from transformers import (
    LogitsProcessorList,
    MinLengthLogitsProcessor,
    BeamSearchScorer,
)

In [4]:
fname = 'data/codex-m/test.txt'
f = open(fname, 'r')
data = []
for line in f:
    data.append(line.strip())
f.close()

In [5]:
len(data)

20622

In [6]:
data[0]

'predict tail: billy idol | languages spoken, written, or signed |\tenglish'

In [7]:
import torch
# data_point = 'predict tail: novalis | occupation |    philosopher'
id = 0
data_point = data[id]
encoder_input_str, target = data_point.split('\t')
encoder_input_str = [encoder_input_str]
encoder_input_ids = tokenizer(encoder_input_str, return_tensors="pt").input_ids
num_beams = 10
num_predictions = 3
input_ids = torch.ones((len(encoder_input_str) * num_beams, 1), device=model.device, dtype=torch.long)
input_ids = input_ids * model.config.decoder_start_token_id
model_kwargs = {
    "encoder_outputs": model.get_encoder()(encoder_input_ids.repeat_interleave(num_beams, dim=0), return_dict=True)
}
beam_scorer = BeamSearchScorer(
    batch_size=len(encoder_input_str),
    max_length=model.config.max_length,
    num_beams=num_beams,
    device=model.device,
    num_beam_hyps_to_keep=num_predictions,
    length_penalty=0.3
)
logits_processor = LogitsProcessorList([])

In [8]:
encoder_input_str

['predict tail: billy idol | languages spoken, written, or signed |']

In [9]:
outputs = model.beam_search(input_ids, beam_scorer, logits_processor=logits_processor, **model_kwargs)
print("Beam:", tokenizer.batch_decode(outputs, skip_special_tokens=True))
outputs = model.generate(encoder_input_ids)
print('Greedy:', tokenizer.batch_decode(outputs, skip_special_tokens=True))
print('Target:', target)

Beam: ['english', 'german', 'british english']
Greedy: ['english']
Target: english


In [10]:
def getGreedyOutput(model, tokenizer, encoder_input_str):
    encoder_input_str = [encoder_input_str]
    encoder_input_ids = tokenizer(encoder_input_str, return_tensors="pt").input_ids
    outputs = model.generate(encoder_input_ids)
    return tokenizer.batch_decode(outputs, skip_special_tokens=True)

In [31]:
def getBeamOutput(model, tokenizer, encoder_input_str, num_beams=10, 
                  num_predictions=3, length_penalty=0.3):
    encoder_input_str = [encoder_input_str]
    encoder_input_ids = tokenizer(encoder_input_str, return_tensors="pt").input_ids
#     encoder_input_ids = tokenizer(encoder_input_str, padding='max_length', truncation=True, max_length=128, return_tensors="pt").input_ids
    input_ids = torch.ones((len(encoder_input_str) * num_beams, 1), device=model.device, dtype=torch.long)
    input_ids = input_ids * model.config.decoder_start_token_id
    model_kwargs = {
        "encoder_outputs": model.get_encoder()(encoder_input_ids.repeat_interleave(num_beams, dim=0), return_dict=True)
    }
    beam_scorer = BeamSearchScorer(
        batch_size=len(encoder_input_str),
        max_length=model.config.max_length,
        num_beams=num_beams,
        device=model.device,
        num_beam_hyps_to_keep=num_predictions,
        length_penalty=length_penalty
    )
    logits_processor = LogitsProcessorList([])
    outputs = model.beam_search(input_ids, beam_scorer, logits_processor=logits_processor, **model_kwargs)
    return tokenizer.batch_decode(outputs, skip_special_tokens=True)

In [26]:
model.eval()

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseReluDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dro

In [32]:
from tqdm import tqdm
# id = 100
scorer_function = getBeamOutput 
# scorer_function = getGreedyOutput 
num_points = 50
correct = 0
for id in tqdm(range(0, num_points)):
    data_point = data[id]
    input, target = data_point.split('\t')
    predicted = set(scorer_function(model, tokenizer, input))
    print(predicted, target)
    if target in predicted:
        correct += 1
print(correct/num_points)

  2%|▏         | 1/50 [00:00<00:15,  3.10it/s]

{'english', 'british english', 'german'} english


  4%|▍         | 2/50 [00:00<00:17,  2.75it/s]

{'edgar allan poe', 'samuel r. delany', 'edward bernard raczynski'} billy idol


  6%|▌         | 3/50 [00:01<00:15,  3.09it/s]

{'writer', 'politician', 'diplomat'} critic


 10%|█         | 5/50 [00:01<00:13,  3.37it/s]

{'eugene ionesco', 'jean-baptiste alphonse karr', 'jean-francois marmontel'} fukuzawa yukichi
{'film actor', 'screenwriter', 'film director'} television actor


 14%|█▍        | 7/50 [00:02<00:11,  3.74it/s]

{'michael keaton', 'sarah michelle gellar', 'michael higgins'} joan fontaine
{'musician', 'singer', 'songwriter'} lyricist


 16%|█▌        | 8/50 [00:02<00:12,  3.32it/s]

{'george gurdjieff', 'joe hisaishi', 'eduardo carrasco'} chara


 18%|█▊        | 9/50 [00:02<00:12,  3.40it/s]

{'multilateral investment guarantee agency', 'organisation of islamic cooperation', 'international bank for reconstruction and development'} commonwealth of nations


 22%|██▏       | 11/50 [00:03<00:10,  3.88it/s]

{'malaysia', 'equatorial guinea', 'botswana'} sri lanka
{'writer', 'television actor', 'podcaster'} children's writer


 26%|██▌       | 13/50 [00:03<00:10,  3.57it/s]

{'edgar allan poe', 'elisabeth langgasser', 'elisabeth mann borgese'} katie couric
{'film actor', 'television actor', 'actor'} singer


 28%|██▊       | 14/50 [00:04<00:10,  3.59it/s]

{'sarah mclachlan', 'taylor swift', 'taylor dayne'} miranda cosgrove


 30%|███       | 15/50 [00:04<00:12,  2.80it/s]

{'russian academy of sciences', 'academy of sciences of the ussr', 'central committee of the communist party of the soviet union'} academy of sciences of the ussr


 34%|███▍      | 17/50 [00:05<00:11,  2.97it/s]

{'konstantin vasilyevich frolov', 'mikhail vasilyevich lomonosov', 'mikhail vassilyevich lomonosov'} s. s. grigorian
{'film actor', 'screenwriter', 'film director'} stage actor


 38%|███▊      | 19/50 [00:05<00:08,  3.64it/s]

{'michael keaton', 'lily collins', 'michael higgins'} georg alexander
{'film actor', 'television actor', 'actor'} voice actor


 40%|████      | 20/50 [00:06<00:08,  3.39it/s]

{'michael keaton', 'taylor lautner', 'sarah michelle gellar'} alaina reed hall


 42%|████▏     | 21/50 [00:06<00:08,  3.58it/s]

{'physicist', 'engineer', 'mathematician'} engineer


 44%|████▍     | 22/50 [00:06<00:08,  3.24it/s]

{'richard friend', 'jean-baptiste biot', 'henry louis le chatelier'} nikolay yegorovich zhukovsky


 46%|████▌     | 23/50 [00:07<00:07,  3.38it/s]

{'south america', 'latin america', 'hispanic america'} hispanic america


 48%|████▊     | 24/50 [00:07<00:07,  3.57it/s]

{'venezuela', 'paraguay', 'uruguay'} chile


 50%|█████     | 25/50 [00:07<00:08,  2.92it/s]

{'united kingdom of great britain and ireland', 'united kingdom', 'united states of america'} united states of america


 52%|█████▏    | 26/50 [00:08<00:09,  2.59it/s]

{'robert moog', 'joel mcneely', 'james cotton'} norman whitfield


 54%|█████▍    | 27/50 [00:08<00:07,  2.96it/s]

{'kleinmachnow', 'munich', 'berlin'} malibu


 58%|█████▊    | 29/50 [00:09<00:05,  3.53it/s]

{'steve buscemi', 'sarah michelle gellar', 'robert downey, jr.'} thomas gottschalk
{'film actor', 'television actor', 'screenwriter'} television actor


 60%|██████    | 30/50 [00:09<00:05,  3.35it/s]

{'michael keaton', 'sarah michelle gellar', 'michael higgins'} judy garland


 62%|██████▏   | 31/50 [00:09<00:05,  3.51it/s]

{'bipolar disorder', 'parkinson disease', "alzheimer's disease"} alzheimer's disease


 64%|██████▍   | 32/50 [00:10<00:05,  3.01it/s]

{'charlie soong', 'george w. bush', 'george h. w. bush'} glen campbell


 66%|██████▌   | 33/50 [00:10<00:05,  2.91it/s]

{'emi', 'roc-a-fella records', 'universal music group'} columbia records


 68%|██████▊   | 34/50 [00:10<00:05,  3.00it/s]

{'david gilmour', 'taylor swift', 'robert petway'} nena


 70%|███████   | 35/50 [00:11<00:05,  2.62it/s]

{'"university of california, berkeley"', 'carnegie mellon university', 'bell labs'} carnegie mellon university


 74%|███████▍  | 37/50 [00:11<00:04,  3.23it/s]

{'charles p. thacker', 'john ousterhout', 'robert sedgewick'} gordon bell
{'guitar', 'piano', 'voice'} voice


 76%|███████▌  | 38/50 [00:12<00:03,  3.13it/s]

{'sarah mclachlan', 'taylor swift', 'taylor dayne'} teddy darby


 78%|███████▊  | 39/50 [00:12<00:03,  3.14it/s]

{'musician', 'singer', 'record producer'} rapper


 82%|████████▏ | 41/50 [00:12<00:02,  3.65it/s]

{"lil' flip", 'tyga', 'jaden smith'} r. kelly
{'film actor', 'television actor', 'actor'} television actor


 86%|████████▌ | 43/50 [00:13<00:01,  4.00it/s]

{'michael keaton', 'sarah michelle gellar', 'michael higgins'} sylvia kristel
{'television actor', 'television presenter', 'screenwriter'} screenwriter


 88%|████████▊ | 44/50 [00:13<00:01,  3.63it/s]

{'michael keaton', 'robert de niro', 'samuel beckett'} amy brenneman


 90%|█████████ | 45/50 [00:14<00:01,  3.50it/s]

{'humboldt university of berlin', 'university of gottingen', 'university of bonn'} university of wroclaw


 92%|█████████▏| 46/50 [00:14<00:01,  2.69it/s]

{'johann gottfried gruber', 'johann friedrich gottfried eiselen', 'johann michael sailer'} alwin schultz


 94%|█████████▍| 47/50 [00:15<00:01,  2.53it/s]

{'united kingdom', 'canada', 'united states of america'} united states of america


 96%|█████████▌| 48/50 [00:15<00:00,  2.38it/s]

{'robert moog', 'joel mcneely', 'james cotton'} emily osment


 98%|█████████▊| 49/50 [00:15<00:00,  2.70it/s]

{'leipzig', 'berlin', 'heidelberg'} berlin


100%|██████████| 50/50 [00:16<00:00,  3.08it/s]

{'johann erich biester', 'wilhelm liebknecht', 'ernst niekisch'} theodor fontane
0.26


In [118]:
outputs.shape

torch.Size([20, 15])

In [71]:
outputs

tensor([[    0,  1038,  2137,    21, 20532,    11,   606,     1]])

Generated: ['international bank for reconstruction and development']


In [3]:
print(input)
print(''.join(tokenizer.convert_ids_to_tokens(outputs[0])))

predict tail: united states of america | member of |
<pad>▁international▁bank▁for▁reconstruction▁and▁development</s>


In [4]:
from dataset import T5_Dataset

In [5]:
valid_dataset = T5_Dataset('test', dataset_name='codex-m')

100%|██████████| 20622/20622 [00:00<00:00, 840393.08it/s]


In [6]:
from eval_accelerate import removePadding, eval

In [7]:
class Args:
    batch_size = 200
args=Args()

In [8]:
acc = eval(model, valid_dataset, args)

100%|██████████| 104/104 [00:59<00:00,  1.74batches/s]


In [9]:
acc

0.10876733585491223

In [8]:
actual = tokenizer("international development association", return_tensors="pt").input_ids[0].numpy()

In [9]:
actual

array([1038,  606, 6028,    1])

In [10]:
predicted = outputs[0][1:].numpy()

In [11]:
predicted

array([ 1038,  2137,    21, 20532,    11,   606,     1])

In [30]:
actual == predicted

array([ True,  True,  True,  True])

In [25]:
actual.numpy()

array([1038,  606, 6028,    1])